# Generated by Django 3.1.7 on 2021-06-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='company',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
